sudo: false
language: python
env:
  - DJANGO=1.9.5
python:
  - "2.7"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
  - pip install psycopg2

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script: python test.py


deploy:
  provider: openshift
  user: josuecevedo@hotmail.com
  password: mayraantonia
  domain: tareaito
  app: python
