sudo: false
language: python
env:
  - DJANGO=1.9.5
python:
  - "2.7"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
  - pip install psycopg2
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_32a52b2fc29a_key -iv $encrypted_32a52b2fc29a_iv  -in config.js.enc -out config.js -d || true'

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_deploy:
- gem install rhc
- yes | rhc setup --server openshift.redhat.com -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
  --create-token --clean --timeout 10000
- yes | rhc env set encrypted_32a52b2fc29a_key=$encrypted_32a52b2fc29a_key -a reborn
  -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
- yes | rhc env set encrypted_32a52b2fc29a_iv=$encrypted_32a52b2fc29a_iv -a reborn
  -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD # can be encrypted
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_APP
