sudo: false
language: python
env:
  - DJANGO=1.9.5
python:
  - "2.7"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
  - pip install psycopg2
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD # can be encrypted
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_APP
