sudo: false
language: python
env:
  - DJANGO=1.9.5
python:
  - "2.7"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
  - pip install psycopg2

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  -python test.py

before_deploy:
- gem install rhc
- yes | rhc setup --server openshift.redhat.com -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
  --create-token --clean --timeout 10000
- yes | rhc env set encrypted_32a52b2fc29a_key=$encrypted_32a52b2fc29a_key -a reborn
  -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
- yes | rhc env set encrypted_32a52b2fc29a_iv=$encrypted_32a52b2fc29a_iv -a reborn
  -l $OPENSHIFT_USER -p $OPENSHIFT_PASS
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_APP
