# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='tema',
            field=models.CharField(default=datetime.datetime(2016, 4, 23, 19, 36, 7, 202488, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
